waypoints:
  - x: -1.98985
    y: -0.470842
    yaw: -3.71224e-06
  - x: 1.64592
    y: -0.479044
    yaw: -0.0277751
  - x: 1.61318
    y: 1.54356
    yaw: 1.5843
  - x: -0.524069
    y: 1.86293
    yaw: 3.14159
  - x: -0.548649
    y: -1.92024
    yaw: -1.5708
